app/urls.py
from django.urls import path
from .views import TaskListView, TagListView, TaskCreateView, TaskUpdateView, TaskDeleteView, complete_undo, \
    TagCreateView, TagUpdateView, TagDeleteView

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/complete-undo/", complete_undo, name="task-complete-undo"),


    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "app"

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

app/models.py
from django.utils import timezone

from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(
        blank=True,
        null=True,
        default=timezone.now() + timezone.timedelta(days=7)
    )
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField('Tag', blank=True, related_name='tasks')

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["done", "-datetime"]


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

app/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, CheckboxSelectMultiple

from app.models import Task, Tag


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from app.forms import TaskForm, TagForm
from app.models import Task, Tag


def complete_undo(request, pk):
    task = get_object_or_404(Task, id=pk)

    if task.done:
        task.done = False
    else:
        task.done = True
    task.save()

    return HttpResponseRedirect(reverse_lazy("app:task-list"))


class TaskListView(ListView):
    model = Task
    template_name = "app/task_list.html"
    context_object_name = "tasks"
    paginate_by = 10
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task-list")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task-list")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("app:task-list")


class TagListView(ListView):
    model = Tag
    template_name = "app/tag_list.html"
    context_object_name = "tags"
    paginate_by = 10


class TagCreateView(CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("app:tag-list")


class TagUpdateView(UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("app:tag-list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("app:tag-list")

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="text-center mt-5">
  <h1>Delete tag?</h1>
  <form action="" method="post" class="mt-3">
    {% csrf_token %}

    <button type="submit" class="btn btn-danger mr-2">Yes</button>
    <a href="{% url "app:tag-list" %}" class="btn btn-secondary">No</a>
  </form>
</div>

{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5">
  <h1 class="display-4 mb-4">
    Tags
    <a href="{% url 'app:tag-create' %}" class="btn btn-secondary link-to-page">
      Add task
    </a>
  </h1>
    <div class="container mt-5">
      {% if tags %}
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Update</th>
                <th>Delete</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for tag in tags %}
                <tr>
                  <td>{{ tag.name }}</td>
                  <td>
                    <a href="{% url 'app:tag-update' pk=tag.id %}" class="btn btn-warning">
                      Update
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'app:tag-delete' pk=tag.id %}" class="btn btn-danger">
                      Delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p class="lead">There are no tags</p>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="text-center mt-5">
  <h1>Delete task?</h1>
  <form action="" method="post" class="mt-3">
    {% csrf_token %}

    <button type="submit" class="btn btn-danger mr-2">Yes</button>
    <a href="{% url "app:task-list" %}" class="btn btn-secondary">No</a>
  </form>
</div>

{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/app/task_list.html
{% extends "base.html" %}
{# {% load crispy_forms_filters %} #}

{% block content %}
    <div class="container mt-5">
        <h1 class="display-4 mb-4">
            TODO list
            <a href="{% url 'app:task-create' %}" class="btn btn-secondary link-to-page">
                Add task
            </a>
        </h1>

        {% if tasks %}
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Task</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                            <tr>

                              <td>
                                  <ul>
                                      <li>
                                          {{ task.content }}
                                          <span class="{% if task.done %}text-success{% else %}text-danger{% endif %}">
                                              {% if task.done %}Done{% else %}Pending{% endif %}
                                          </span>
                                      </li>                                      <li>{{ task.datetime }}</li>
                                      <li>Deadline: {{ task.deadline }}</li>
                                      <li>
                                          Tags: {{ task.tags.all|join:", " }}
                                      </li>
                                      <br>
                                      <a href="{% url 'app:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">Update</a>
                                      <a href="{% url 'app:task-delete' pk=task.id %}" class="btn btn-danger link-to-page ml-2">Delete</a>


                                      <!-- Add other task properties as needed -->
                                  </ul>
                              </td>



                                <td>
                                    {% if task.done %}
                                        <a href="{% url 'app:task-complete-undo' pk=task.id %}" class="btn btn-secondary link-to-page">
                                            Undo
                                        </a>
                                    {% else %}
                                        <a href="{% url 'app:task-complete-undo' pk=task.id %}" class="btn btn-success link-to-page">
                                            Complete
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="lead">There are no tasks</p>
        {% endif %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>
        body {
            background-image: url('{% static "img/background.jpg" %}');
            /* Replace "images/background.jpg" with the actual path to your background image */
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>

<body class="bg-light">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    {% include "includes/sidebar.html" %}
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}
                {% block pagination %}
                    {% include "includes/pagination.html" %}
                {% endblock %}
                {% include "includes/footer.html" %}
            </div>
        </div>
    </div>
</body>

</html>

templates/includes/footer.html
<footer class="mt-5">
    <!-- Your footer content goes here -->
    <p>&copy; 2023 Kitaiskyi Oleksii</p>
</footer>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">⬅️</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link text-primary bg-light">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">➡️</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group bg-light">
  <li class="list-group-item"><a href="{% url 'app:task-list' %}" class="text-dark">Home</a></li>
  <li class="list-group-item"><a href="{% url 'app:tag-list' %}" class="text-dark">Tags</a></li>
</ul>